### ISSUE TITLE
Guys the web link is broken

### ISSUE THREAD

**Issue by mfrw** [LinuxChixIndia/LinuxChixIndia.github.io#15] opened 2017-05-23 01:58 UTC
The website for linuxchixindia is broken, I tried to access it but it failed.

**Comment by CuriousLearner** [comment] 2017-05-23 02:43
It is in process of being migrated to a custom domain. 
We will see to it :) 

Thanks

**Comment by CuriousLearner** [comment] 2017-05-23 05:04
Let's keep it open till the issue is actually fixed.

Currently A records of the domain have to be mapped to Github and DNS propagation would require 24-48 hours.

Once it is resolved we will close this issue. 

Thanks!

**Comment by mfrw** [comment] 2017-05-23 05:07
Sure ... I closed it as I thought it was a known issue.

**Comment by CuriousLearner** [comment] 2017-05-23 05:09
Yeah, known to us, not to everyone :) 

Just to ensure others don't open up the same issue, it's better to keep it open. :)

Thanks for noticing this @mfrw

**Comment by CuriousLearner** [comment] 2017-06-01 15:35
This is resolved now.

Website has been mapped to http://india.linuxchix.org/

Thanks @shivan1b !

PS: In case someone has still issues, please wait for at least 48 hours from now to let the DNS entries fully propagate. If you still face this issue after that, please consider re-opening this thread.

**Closed as completed by CuriousLearner** 2017-06-01 15:35 UTC
